---
- name: Sentry | Running database migrations
  command: "./sentry --config {{ sentry_configuration_path }} upgrade --noinput"
  args:
    chdir: "{{ sentry_installation_path }}/bin/"
  when: sentry_pip_result.changed
  tags:
    - skip_ansible_lint

- name: Sentry | Creating admin users
  command:
    "./sentry --config {{ sentry_configuration_path }} createuser \
    --email {{ item.email }} \
    --password {{ item.password }} \
    {{ '--superuser' if item.superuser else ''}} \
    --no-input"
  args:
    chdir: "{{ sentry_installation_path }}/bin/"
  loop: "{{ sentry_admin_users }}"
  no_log: yes
  ignore_errors: yes
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Sentry | Setting cleanup task
  cron:
    name: Sentry Cleanup
    job: "SENTRY_CONF={{ sentry_configuration_path }} {{ sentry_installation_path }}/bin/sentry cleanup --days {{ sentry_cleanup_keep_days }}"
    state: present
    minute: "{{ sentry_cleanup_cron.minute }}"
    hour: "{{ sentry_cleanup_cron.hour }}"
    day: "{{ sentry_cleanup_cron.day }}"
    month: "{{ sentry_cleanup_cron.month }}"
    weekday: "{{ sentry_cleanup_cron.weekday }}"
