---

pg_major_release: 9.6
pg_os_tuning: false

pg_listen_addresses: "0.0.0.0"

pg_databases:
  - name: sentry

pg_users:
  - name: "{{ sentry_postgresql_database.user }}"
    password: "{{ sentry_postgresql_database.password }}"
    role_attr_flags: SUPERUSER

pg_hba_declarations:
  - "host sentry {{ sentry_postgresql_database.user }} {{ hostvars['sentryserver']['ansible_all_ipv4_addresses'][0] }}/32 password"
