---
postgresql_databases:
  - name: sentry

postgresql_users:
  - name: "{{ sentry_postgresql_database.user }}"
    password: "{{ sentry_postgresql_database.password }}"
    role_attr_flags: SUPERUSER


hba_entry:
  - type: host
    database: sentry
    user: "{{ sentry_postgresql_database.user }}"
    address: "{{ hostvars['sentryserver']['ansible_facts']['default_ipv4']['address'] }}/32"
    auth_method: password


