---
- name: Gathering facts
  hosts: all
  gather_facts: yes

- name: Prepare PostgreSQL
  hosts: sentry_postgresql
  pre_tasks:
    - name: Set var
      set_fact:
        postgresql_hba_entries: "{{ postgresql_hba_entries | default([]) | union(hba_entry) }}"
  roles:
    - role: postgresql
      become: yes
  post_tasks:
    - name: Change listen ip
      lineinfile:
        path: /etc/postgresql/9.6/main/postgresql.conf
        regexp: '^listen_addresses'
        insertafter: '^#listen_addresses'
        line: "listen_addresses = '0.0.0.0'"
      notify: restart postgresql

- name: Prepare Redis
  hosts: sentry_redis
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    - redis
